#!/bin/bash
export DEBIAN_FRONTEND="noninteractive"

#Update Packages
apt-get update

#Install Prerequisite Software
apt-get -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

