apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: example-source
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/kmbeducative/system
  ref:
    branch: main