apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: example-kustomization
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-source
  targetNamespace: default