apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-deployment
  namespace: production
  labels:
    app: pricing-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pricing-app
  template:
    metadata:
      labels:
        app: pricing-app
    spec:
      containers:
      - name: pricing-app
        image: myregistry.azurecr.io/pricing-app:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 2