apiVersion: v1
kind: Service
metadata:
  name: pricing-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: pricing-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000